"""
Тип ошибки 3: Неправильное использование генераторного выражения

Если передать генераторное выражение напрямую в функции, которые используют итерацию,
оно может быть истощено до того, как мы сможем его повторно использовать.
"""

gen = (x ** 2 for x in range(5))
print(sum(gen))  # Генератор истощён
print(list(gen))  # [] (генератор уже пуст)

"""
Решение:

Сохраните результат, если требуется повторное использование.
"""

gen = (x**2 for x in range(5))
result = list(gen)  # Сохраняем результат
print(sum(result))  # 30
print(result)  # [0, 1, 4, 9, 16]



def infinite_numbers():
    num = 1
    while True:
        yield num
        num += 1


gen = infinite_numbers()
for n in gen:
    print(n)  # Никогда не завершится